version: 2
jobs:
  asb:
    machine: true
    steps:
      - checkout
      - run: ./.circleci/main.sh

  voting:
    machine: true
    steps:
      - checkout
      - run: ./.circleci/voting.sh
      - store_artifacts:
          path: _out
          destination: test-output
workflows:
  version: 2
  commit:
    jobs:
      - asb
      - voting
