version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.4
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
          - yarn-cache-{{ .Branch }}
          - yarn-cache-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: yarn-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn test
      - store_artifacts:
          path: ganache.log
